scrapyd:
  image: raflman/scrapyd:pillow
  ports:
    - "6800:6800"
  volumes:
    - ./data:/scrapyd
    - scrapyd-pillow-packages:/usr/lib/python3.6/site-packages
  restart: always

scrapy:
  image: raflman/scrapyd
  command: sh
  volumes:
    - .:/code
    - scrapyd-pillow-packages:/usr/lib/python3.6/site-packages
  working_dir: /code
  restart: always